-- SPDX-License-Identifier: Apache-2.0
--
-- Round-trip cost by notional, over one hour of pump.fun trades.
--
-- Carried rather than described, for the reason 0013 gives: a note whose query
-- exists only in prose is one nobody can re-run, and re-running is the only way
-- a number in a note gets checked. This file exists because the measurement
-- behind `assumed_round_trip_bps = 850` did NOT exist, and could not be checked.
--
-- Generated by `radar cost --from <ts> --to <ts>`; this is the statement it
-- issues, with the window and program substituted.
--
-- Cost is the gap between the largest outflow and the largest inflow of the
-- transaction: protocol fee, priority fee, account rent and slippage together.
-- Approximate in the way the original measurement was -- it attributes the
-- largest inflow/outflow pair to the trade, so it also captures rent and any
-- second hop.
--
-- Read `median_bps` and `median_lamports` against each other. A purely
-- proportional cost is flat in bps and grows in lamports; a fixed one is flat in
-- lamports and falls in bps as the notional rises.

WITH ix AS (
    SELECT DISTINCT tx_signature
    FROM solana.instructions
    WHERE program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
      AND block_timestamp >= '2026-08-25 04:00:00'
      AND block_timestamp <  '2026-08-25 05:00:00'
      -- pump.fun trade discriminators, from `Scope::Trades`.
      AND lower(hex(substring(base58Decode(data), 1, 8))) IN ('66063d1201daebea', '33e685a4017f83ad')
), legs AS (
    SELECT -arrayMin(arrayMap(x -> toInt128(x.3 - x.2), balance_changes)) AS outflow,
            arrayMax(arrayMap(x -> toInt128(x.3 - x.2), balance_changes)) AS inflow
    FROM solana.transactions
    WHERE block_timestamp >= '2026-08-25 04:00:00'
      AND block_timestamp <  '2026-08-25 05:00:00'
      -- `err = ''` is the success test; there is no `succeeded` column.
      AND err = ''
      AND signature IN (SELECT tx_signature FROM ix)
)
SELECT toString(roundDown(toUInt64(outflow), [1000000, 10000000, 100000000, 1000000000, 10000000000])) AS bucket_lamports,
       toString(count())                                                        AS fills,
       toString(toUInt64(quantileExact(0.5)((outflow - inflow) * 10000 / outflow))) AS median_bps,
       toString(toUInt64(quantileExact(0.5)(outflow - inflow)))                 AS median_lamports
FROM legs
-- A leg that received more than it sent is not a cost, and a zero outflow would
-- divide.
WHERE outflow > 0 AND outflow >= inflow
GROUP BY roundDown(toUInt64(outflow), [1000000, 10000000, 100000000, 1000000000, 10000000000])
ORDER BY roundDown(toUInt64(outflow), [1000000, 10000000, 100000000, 1000000000, 10000000000]);
